---
applications:
- name: tsp-subscriber-service
  path: ../subscriber-service/target/subscriber-service-1.0.0-SNAPSHOT-exec.jar
  host: tsp-subscriber-service-qa
  timeout: 180
  memory: 1024M
  disk_quota: 1024M
  instances: 1
env:
  JAVA_OPTS: '-Dspring.profile.active=local'
